# Generated by Django 2.1.4 on 2018-12-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя бренда')),
                ('alias_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя категории товара')),
                ('alias_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='имя продукта')),
                ('short_desc', models.CharField(blank=True, max_length=128, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='подробно')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('img_big', models.ImageField(blank=True, upload_to='big_img')),
                ('img_s_1', models.ImageField(blank=True, upload_to='small_img_1')),
                ('img_s_2', models.ImageField(blank=True, upload_to='small_img_2')),
                ('img_s_3', models.ImageField(blank=True, upload_to='small_img_3')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BrandProduct')),
                ('catecory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CategoryProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='тип продукта')),
                ('alias_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
        ),
    ]
